version: '3.8'

services:

#  db:
#    container_name: mongo_db
#    image: mongo:latest
#    env_file:
#      - ./.env
#    environment:
#      - MONGO_DB_URL=${MONGO_DB_URL}
#      - MONGO_DB_NAME=${MONGO_DB_NAME}
#    ports:
#      - "27017:27017"
#    restart: "always"
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    command:
      mongod --quiet --logpath /dev/null
    volumes:
      - mongo_data:/var/lib/mongo/data/


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parsers
    env_file:
      - ./.env
    expose:
      - "8001"
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    restart: "always"

volumes:
  mongo_data: