import os


MONGO_INITDB_DATABASE = os.getenv('MONGO_INITDB_DATABASE')
MONGO_INITDB_ROOT_USERNAME = os.getenv('MONGO_INITDB_ROOT_USERNAME')
MONGO_INITDB_ROOT_PASSWORD = os.getenv('MONGO_INITDB_ROOT_PASSWORD')
MONGO_INITDB_PORT = os.getenv('MONGO_INITDB_PORT')
MONGO_INITDB_HOST = os.getenv('MONGO_INITDB_HOST')

MONGO_URI = (f"{MONGO_INITDB_DATABASE}://"
             + f"{MONGO_INITDB_ROOT_USERNAME}:"
             + f"{MONGO_INITDB_ROOT_PASSWORD}"
             + f"@{MONGO_INITDB_DATABASE}:{MONGO_INITDB_PORT}")